INSERT OR REPLACE INTO tours (id, name, status, cover, description, announcement_at, start_at, end_at, album_ids_json, setlists_json)
VALUES ('48291357', 'The Eras Tour', 1, '/assets/images/ui/avatar-placeholder.png', '一场横跨全部音乐时期的“时代回顾”巡演，用超长时长与高完成度舞台串联起 Taylor 的完整创作宇宙，也成为流行文化现象级事件。', 1768406400000, 1772294400000, 1788019200000, '[]', '[{"label":"2023.3-2024.3","songs":["Miss Americana & The Heartbreak Prince","Cruel Summer","The Man","You Need To Calm Down","Lover","The Archer","Fearless","You Belong With Me","Love Story","''tis the damn season","willow","marjorie","champagne problems","tolerate it","...Ready For It?","Delicate","Don''t Blame Me","Look What You Made Me Do","Enchanted","Long Live","22","We Are Never Ever Getting Back Together","I Knew You Were Trouble","All Too Well (10 Minute Version)","the 1","betty","the last great american dynasty","august","illicit affairs","my tears ricochet","cardigan","Style","Blank Space","Shake It Off","Wildest Dreams","Bad Blood","Guitar Surprise Song","Piano Surprise Song","Lavender Haze","Anti-Hero","Midnight Rain","Vigilante Shit","Bejeweled","Mastermind","Karma"]},{"label":"2024.5-2024.12","songs":["Miss Americana & The Heartbreak Prince","Cruel Summer","The Man","You Need To Calm Down","Lover","Fearless","You Belong With Me","Love Story","22","We Are Never Ever Getting Back Together","I Knew You Were Trouble","All Too Well (10 Minute Version)","Enchanted","...Ready For It?","Delicate","Don''t Blame Me","Look What You Made Me Do","cardigan","betty","champagne problems","august","illicit affairs","my tears ricochet","marjorie","willow","Style","Blank Space","Shake It Off","Wildest Dreams","Bad Blood","But Daddy I Love Him","So High School","Who''s Afraid of Little Old Me?","Down Bad","Fortnight","The Smallest Man Who Ever Lived","I Can Do It With a Broken Heart","Guitar Surprise Song/Mashup","Piano Surprise Song/Mashup","Lavender Haze","Anti-Hero","Midnight Rain","Vigilante Shit","Bejeweled","Mastermind","Karma"]}]');

INSERT OR REPLACE INTO tours (id, name, status, cover, description, announcement_at, start_at, end_at, album_ids_json, setlists_json)
VALUES ('73160584', 'Reputation Stadium Tour', 2, '/assets/images/ui/avatar-placeholder.png', '她首次全体育场巡演，整体风格更锋利、黑暗又张扬，以强烈的视觉冲击和掌控感重塑了 “Reputation” 时代的舞台形象。', NULL, 1525708800000, 1542729600000, '[]', '[{"label":"标准歌单","songs":["...Ready For It?","I Did Something Bad","Gorgeous","Style / Love Story / You Belong With Me","Look What You Made Me Do","End Game","King Of My Heart","Delicate","Shake It Off","Dancing With Our Hands Tied","Surprise Song","Blank Space","Dress","Bad Blood / Should''ve Said No","Don''t Blame Me","Long Live / New Year''s Day","Why She Disappeared","Getaway Car","Call It What You Want","We Are Never Ever Getting Back Together / This Is Why We Can''t Have Nice Things"]}]');

INSERT OR REPLACE INTO tours (id, name, status, cover, description, announcement_at, start_at, end_at, album_ids_json, setlists_json)
VALUES ('26490831', 'The 1989 World Tour', 2, '/assets/images/ui/avatar-placeholder.png', '以彻底流行化的《1989》为核心，这场巡演充满都市感、流行能量与巨星气场，标志着 Taylor 正式进入全球顶流时代。', 1414944000000, 1430755200000, 1449849600000, '[]', '[{"label":"标准歌单","songs":["Welcome To New York","New Romantics","Blank Space","I Knew You Were Trouble","I Wish You Would","How You Get The Girl","I Know Places","All You Had To Do Was Stay","Surprise Song","Clean","Love Story","Style","This Love","Bad Blood","We Are Never Ever Getting Back Together","Enchanted / Wildest Dreams","Out Of The Woods","Shake It Off"]}]');

INSERT OR REPLACE INTO tours (id, name, status, cover, description, announcement_at, start_at, end_at, album_ids_json, setlists_json)
VALUES ('59014276', 'The Red Tour', 2, '/assets/images/ui/avatar-placeholder.png', '这是 Taylor 从乡村转向主流流行的重要阶段巡演，情绪更浓烈、视觉更鲜明，也让 “Red era” 成为最具代表性的成长篇章之一。', 1351094400000, 1363104000000, 1402502400000, '[]', '[{"label":"标准歌单","songs":["State Of Grace","Holy Ground","Red","You Belong With Me","The Lucky One","Mean","Stay Stay Stay / Ho Hey","22","Surprise Song","Everything Has Changed","Begin Again","Sparks Fly","I Knew You Were Trouble","All Too Well","Love Story","Treacherous","We Are Never Ever Getting Back Together"]}]');

INSERT OR REPLACE INTO tours (id, name, status, cover, description, announcement_at, start_at, end_at, album_ids_json, setlists_json)
VALUES ('81732465', 'Speak Now World Tour', 2, '/assets/images/ui/avatar-placeholder.png', '一场更具戏剧感与童话色彩的世界巡演，把《Speak Now》时期的浪漫、自我表达与舞台叙事推向了新的高度。', 1290441600000, 1297180800000, 1332000000000, '[]', '[{"label":"标准歌单","songs":["Sparks Fly","Mine","The Story Of Us","Our Song","Mean","Back To December / Apologize / You''re Not Sorry","Better Than Revenge","Speak Now","Fearless / I''m Yours / Hey, Soul Sister","Last Kiss","You Belong With Me","Dear John","Enchanted","Haunted","Long Live","Fifteen","Love Story"]}]');

INSERT OR REPLACE INTO tours (id, name, status, cover, description, announcement_at, start_at, end_at, album_ids_json, setlists_json)
VALUES ('14685723', 'Fearless Tour', 2, '/assets/images/ui/avatar-placeholder.png', 'Taylor 首次大型个人巡演，以青春、真诚与乡村流行气质为核心，奠定了她早期“少女叙事”式现场风格。', 1233158400000, 1240416000000, 1278691200000, '[]', '[{"label":"标准歌单","songs":["You Belong With Me","Our Song","Tell Me Why","Teardrops On My Guitar","Fearless","Forever & Always","Hey Stephen","Fifteen","Tim McGraw","White Horse","Love Story","The Way I Loved You","You''re Not Sorry","Picture To Burn","I''m Only Me When I''m With You","Should''ve Said No"]}]');
